### PR TITLE
ace support

### PR DESCRIPTION
**Pull request by AlexRuppert**
supports ace via bindAce()

### CODE REVIEW

**Comment by istvank** [comment]
What functionality is added with this pull request?

**Comment by dmonad** [comment]
Support for infamous Ace editor of course ;)

**Comment by istvank** [comment]
Ah! Right, now I remember. Wouldn't it be better to put it in an external module or something? Because such a non-HTML5 bind is rather framework-specific. On the other hand, in y-richtext you bind to quill instances in the same way if I remember correctly.

**Comment by dmonad** [comment]
Ace support is just a few lines of code. I think it is the right choice to put everything in y-text, that has a text-like structure. At some point (when the codebase is too large), we might want to outsource the bindings in y-text-ace. but that's not necessary right now

**Comment by nicolaescu** [comment]
True, this is also what I asked myself when seeing the message..
Wouldn't it be nicer to have Y-text independent of specific editors?

On 02.02.2016 15:58, István Koren wrote:

> Ah! Right, now I remember. Wouldn't it be better to put it in an 
> external module or something? Because such a non-HTML5 bind is rather 
> framework-specific. On the other hand, in y-richtext you bind to quill 
> instances in the same way if I remember correctly.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/y-js/y-text/pull/1#issuecomment-178617049.

## 

Petru Nicolaescu, M.Sc.

Advanced Community Information Systems (ACIS)
Chair for Computer Science 5 (Information Systems & Databases)
Room 6239
RWTH Aachen
Ahornstr. 55    52056 Aachen
Germany
Email: nicolaescu@dbis.rwth-aachen.de
Tel:     +49 (0) 241 80 21516

**Comment by nicolaescu** [comment]
Cool, not sure if this is done - but can you please document the code 
such that we won't forget when outsourcing at some later stage ^^ ... 
then it would probably be traceable for someone who checks out and uses 
the y-text and doesn't expect the ace editor there.
Thanks! :)

On 02.02.2016 16:00, Kevin Jahns wrote:

> Ace support is just a few lines of code. I think it is the right 
> choice to put everything in y-text, that has a text-like structure. At 
> some point (when the codebase is too large), we might want to 
> outsource the bindings in y-text-ace. but that's not necessary right now
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/y-js/y-text/pull/1#issuecomment-178618230.

## 

Petru Nicolaescu, M.Sc.

Advanced Community Information Systems (ACIS)
Chair for Computer Science 5 (Information Systems & Databases)
Room 6239
RWTH Aachen
Ahornstr. 55    52056 Aachen
Germany
Email: nicolaescu@dbis.rwth-aachen.de
Tel:     +49 (0) 241 80 21516

**Comment by dmonad** [comment]
Sure

**Comment by AlexRuppert** [comment]
What about sub-modules for YText (and potentially others), where you can register custom bindings like `Y.Text.extend('ace', ...)` and use them like
`y.share.text.bind.ace(node)` or `y.share.text.bind.textarea(node)`, since code elements, like insert and delete, can be shared among most editors and only a specific implementation of required API calls is needed? I think for now the 'put it in y-text'-approach should be sufficient, but for the future it surely might look a bit crammed.

**Comment by istvank** [comment]
Thanks @AlexRuppert that's exactly what I was thinking about. :+1:

**Pull request merged**
